version: '3.4'
networks:
  mynet:
services:
  urlshortnerservice:
    image: urlshortnerservice
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    networks:
      - mynet
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 54004:5432
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    networks:
      - mynet
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: url_shortner

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

